#!/usr/bin/env python3
"""
배치 처리용 STORM 연구 스크립트
여러 주제를 한번에 처리할 수 있습니다.
"""

import asyncio
import json
import time
from datetime import datetime
from typing import List, Dict
from storm_research import ParallelStormResearchSystem

# 예시 주제들
EXAMPLE_TOPICS = [
    "인공지능의 의료 진단 분야 활용과 한계",
    "블록체인 기술의 금융 산업 혁신 사례",
    "양자 컴퓨팅이 암호화 기술에 미치는 영향",
    "메타버스 플랫폼의 기술적 구현과 사회적 함의",
    "ESG 경영과 지속가능한 비즈니스 모델"
]

async def batch_storm_research(topics: List[str], max_concurrent: int = 2) -> Dict[str, str]:
    """여러 주제에 대해 순차적으로 STORM 연구 수행"""
    results = {}
    
    print(f"🎯 배치 처리 시작: {len(topics)}개 주제")
    print(f"📊 최대 동시 처리: {max_concurrent}개")
    print("-" * 60)
    
    # 세마포어로 동시 실행 수 제한
    semaphore = asyncio.Semaphore(max_concurrent)
    
    async def process_single_topic(topic: str) -> tuple:
        """단일 주제 처리"""
        async with semaphore:
            print(f"\n🔄 시작: {topic}")
            start_time = time.time()
            
            storm_system = ParallelStormResearchSystem(max_workers=3)  # 배치용으로 워커 수 감소
            
            try:
                result = await storm_system.run_parallel_storm_research(
                    topic=topic,
                    enable_human_loop=False  # 배치 모드에서는 자동 실행
                )
                
                duration = time.time() - start_time
                print(f"✅ 완료: {topic} ({duration:.1f}초)")
                
                return topic, result
                
            except Exception as e:
                print(f"❌ 실패: {topic} - {e}")
                return topic, f"오류 발생: {e}"
                
            finally:
                await storm_system.model_client.close()
                await storm_system.long_context_model.close()
    
    # 모든 작업을 병렬로 시작하되, 세마포어로 제한
    tasks = [process_single_topic(topic) for topic in topics]
    
    # 결과 수집
    completed_results = await asyncio.gather(*tasks, return_exceptions=True)
    
    for result in completed_results:
        if isinstance(result, tuple):
            topic, content = result
            results[topic] = content
        else:
            print(f"❌ 예외 발생: {result}")
    
    return results

def save_batch_results(results: Dict[str, str], batch_name: str = None):
    """배치 결과를 파일들로 저장"""
    if not batch_name:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        batch_name = f"batch_{timestamp}"
    
    # 개별 파일로 저장
    for i, (topic, content) in enumerate(results.items(), 1):
        safe_topic = topic.replace(" ", "_").replace("/", "_").replace(":", "_")
        filename = f"{batch_name}_{i:02d}_{safe_topic}.md"
        
        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"# {topic}\n\n")
            f.write(f"*Generated by STORM Research System - Batch: {batch_name}*\n\n")
            f.write(content)
    
    # 요약 보고서 생성
    summary_filename = f"{batch_name}_summary.json"
    summary = {
        "batch_name": batch_name,
        "timestamp": datetime.now().isoformat(),
        "total_topics": len(results),
        "successful": sum(1 for content in results.values() if not content.startswith("오류")),
        "failed": sum(1 for content in results.values() if content.startswith("오류")),
        "topics": list(results.keys())
    }
    
    with open(summary_filename, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)
    
    print(f"\n📋 배치 결과 저장 완료:")
    print(f"   • 개별 파일: {len(results)}개")
    print(f"   • 요약 보고서: {summary_filename}")
    print(f"   • 성공: {summary['successful']}개")
    print(f"   • 실패: {summary['failed']}개")

async def main():
    """메인 함수"""
    print("🌩️ STORM 배치 처리 시스템")
    print("=" * 60)
    
    # 사용자 입력 또는 예시 주제 사용
    use_examples = input("예시 주제들을 사용하시겠습니까? (y/n): ").lower() == 'y'
    
    if use_examples:
        topics = EXAMPLE_TOPICS
        print(f"\n📝 예시 주제 {len(topics)}개를 사용합니다:")
        for i, topic in enumerate(topics, 1):
            print(f"   {i}. {topic}")
    else:
        topics = []
        print("\n주제를 입력하세요 (빈 줄 입력 시 종료):")
        while True:
            topic = input(f"주제 {len(topics)+1}: ").strip()
            if not topic:
                break
            topics.append(topic)
        
        if not topics:
            print("주제가 입력되지 않았습니다.")
            return
    
    # 동시 처리 수 설정
    max_concurrent = int(input(f"\n최대 동시 처리 수 (1-{min(len(topics), 4)}): ") or "2")
    max_concurrent = max(1, min(max_concurrent, 4))  # 1-4 사이로 제한
    
    # 배치 이름 설정
    batch_name = input("배치 이름 (선택사항): ").strip()
    
    print(f"\n🚀 배치 처리를 시작합니다...")
    start_time = time.time()
    
    # 배치 실행
    results = await batch_storm_research(topics, max_concurrent)
    
    # 결과 저장
    save_batch_results(results, batch_name)
    
    # 최종 통계
    total_time = time.time() - start_time
    print(f"\n🏁 배치 처리 완료!")
    print(f"   • 총 소요시간: {total_time:.1f}초")
    print(f"   • 주제당 평균: {total_time/len(topics):.1f}초")

if __name__ == "__main__":
    asyncio.run(main())
