services:
  - type: web
    name: autogen-research-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app_interactive.py"
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health