#!/usr/bin/env python3
"""
간단한 STORM 연구 실행 스크립트
사용법: python simple_run.py "주제명"
"""

import asyncio
import sys
import os
from storm_research import ParallelStormResearchSystem

async def simple_storm_research(topic: str, auto_mode: bool = False):
    """간단한 STORM 연구 실행"""
    print(f"🌩️ STORM 연구 시작: {topic}")
    print("-" * 60)
    
    # 시스템 초기화
    storm_system = ParallelStormResearchSystem(max_workers=4)
    
    try:
        # 연구 실행
        final_article = await storm_system.run_parallel_storm_research(
            topic=topic,
            enable_human_loop=not auto_mode  # auto_mode가 True면 human_loop 비활성화
        )
        
        # 결과 저장
        safe_filename = topic.replace(" ", "_").replace("/", "_").replace(":", "_")
        filename = f"storm_result_{safe_filename}.md"
        
        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"# {topic}\n\n")
            f.write(f"*Generated by STORM Research System*\n\n")
            f.write(final_article)
        
        print(f"\n✅ 연구 완료! 결과 파일: {filename}")
        
        return final_article
        
    except Exception as e:
        print(f"❌ 오류 발생: {e}")
        return None
        
    finally:
        # 리소스 정리
        await storm_system.model_client.close()
        await storm_system.long_context_model.close()

def main():
    """메인 함수"""
    if len(sys.argv) < 2:
        print("사용법: python simple_run.py \"주제명\" [--auto]")
        print("\n예시:")
        print("  python simple_run.py \"인공지능의 의료 분야 활용\"")
        print("  python simple_run.py \"블록체인 기술\" --auto")
        sys.exit(1)
    
    topic = sys.argv[1]
    auto_mode = "--auto" in sys.argv
    
    if auto_mode:
        print("🤖 자동 모드: 사용자 개입 없이 실행됩니다.")
    else:
        print("🤝 대화형 모드: 중간에 승인 과정이 있습니다.")
    
    # 환경 변수 체크
    if not os.getenv("AZURE_OPENAI_API_KEY"):
        print("❌ AZURE_OPENAI_API_KEY가 설정되지 않았습니다.")
        print("   .env 파일을 확인하거나 환경 변수를 설정하세요.")
        sys.exit(1)
    
    # 비동기 실행
    asyncio.run(simple_storm_research(topic, auto_mode))

if __name__ == "__main__":
    main()
